### ISSUE TITLE
Query is no longer returning data

### ISSUE THREAD

**Issue by LukeXF** [Aronnn/Minecraft-Server-Status#1]
`https://aron.li/mss/ping.php` is no longer an active website and returns no data. Did you take your site down Aron?

**Comment by Aronnn** [comment]
Hey,
The site got taken down because my domain registar had some troubles renewing it. However, I did release a new version with a different API just a few weeks ago. I suggest you download it from the chrome webstore and it should work, tell me if you are having problems with that.

**Comment by LukeXF** [comment]
Yer I looked into that shortly after creating this issue. Turns out the site was down for that API as well. But al teast the domain is up and CloudFlare returning errors so I assume it was only down momentarily. Thanks for you continued commitment to keeping the server viewer running, makes my life a lot easier.

I'll check out the other API again shortly.

**Comment by LukeXF** [comment]
The old API seems to of come back online? Sweet

**Comment by Aronnn** [comment]
Yea, if I get the time I will probably rewrite my own API to be a bit more efficient and then switch it over again, this was just a temporary solution as my server could not handle the load.

**Comment by LukeXF** [comment]
Much appreciated, again as we discussed I do have server to help you out with the load if needed. It's completely up to you, but I am here to support your API if you need it.
